name: 'Create build container Window (Linux cross compilation)'

on:
  push:
    paths:
      - 'container/linux_win_cross.Dockerfile'
      - '.github/workflows/create-build-container-win.yaml'

  pull_request:
    paths:
      - 'container/linux_win_cross.Dockerfile'
      - '.github/workflows/create-build-container-win.yaml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: container/linux_win_cross.Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ghcr.io/${{ github.repository }}/build-container-win:latest

